### ISSUE TITLE
Countries appearing twice in RAW data

### ISSUE THREAD

**Issue by tumblerer** [kyotoprotocol/KyotoUI#24]
After running a basic simulation, country are appearing twice in the raw data.  Once with 10 ticks worth of results, and once with 300 ticks,

FinishTime = 300

**Comment by tumblerer** [comment]
Ok, apparently this is because data is never dropped form the database.

We're reinstalling over the same database ID, so the RAW data is being appended onto the end

**Comment by revitteth** [comment]
@webbo89 has just pushed a fix on the initialise page - now offers you the option to initialise (via the initialise page) with a new id (basically the same as copying the default). So although the database is never dropped you will have different simID for each of your simulations.
