### ISSUE TITLE
RAW Data carbonOutput values

### ISSUE THREAD

**Issue by tumblerer** [kyotoprotocol/KyotoUI#25]
The values of carbonOutput and emissionsTarget in the RAW data are nonsense.

It displays values in the region of E72, when its really E11/12

**Comment by webbo89** [comment]
We're due to do a CSV update but had waited while it seemed quite likely to change @maxrev17 could possibly push a new defaultsim.csv?

**Comment by tumblerer** [comment]
Ok, the problem is just a 1 being appended to the RAW data view.
